In [4]:
#Brute force
#T.C:O(n ^3)
#method definition
def brute_force_matrixmul(A,B):
    n=len(A)
    C=[[0]*n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            for k in range(0,n):
                C[i][j] +=A[i][k]*B[k][j]
    return C

#driver code
A=[[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]]
B=[[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]]
print(brute_force_matrixmul(A,B))

[[10, 10, 10, 10], [20, 20, 20, 20], [30, 30, 30, 30], [40, 40, 40, 40]]


In [15]:
#Divide and Conquer Approach
#uses 8 recursive calls
#T.C:O(n^3)
#method definition for split matrix

def split_matrix(M):
    mid=len(M)//2
    M11 = [row[:mid] for row in M[:mid]]
    M12 = [row[mid:] for row in M[:mid]]
    M21 = [row[:mid] for row in M[mid:]]
    M22 = [row[mid:] for row in M[mid:]]
    return M11, M12, M21, M22
#method definiton for add matrix

def add_matrix(A, B):
    n = len(A)
    return [[A[i][j] + B[i][j] for j in range(n)] for i in range(n)]
        
#combining all results
def combine_quadrants(C11, C12, C21, C22):
    top = [C11[i] + C12[i] for i in range(len(C11))]
    bottom = [C21[i] + C22[i] for i in range(len(C21))]
    return top + bottom


def matrix_mul_dc(A,B):
    n=len(A)
    if n==1:
        return [[A[0][0]*B[0][0]]]
    a,b,c,d=split_matrix(A)
    e,f,g,h=split_matrix(B)
    #recursive calls
    c11=add_matrix(matrix_mul_dc(a,e),matrix_mul_dc(b,g))
    c12=add_matrix(matrix_mul_dc(a,f),matrix_mul_dc(b,h))
    c21=add_matrix(matrix_mul_dc(c,e),matrix_mul_dc(d,g))
    c22=add_matrix(matrix_mul_dc(c,f),matrix_mul_dc(d,h))
    #combine results
    return combine_quadrants(c11,c12,c21,c22)
    
    
    
#driver code
A=[[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]]
B=[[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]]
print(matrix_mul_dc(A,B))

[[10, 10, 10, 10], [20, 20, 20, 20], [30, 30, 30, 30], [40, 40, 40, 40]]


In [22]:
#Strassens Multiplication
#T.C:O(n^2.81)
#instead of 8-recursive calls in d&c,strassens use 7 product recursive call
import numpy as np

def split(matrix):
    """Split matrix into 4 quadrants"""
    row, col = matrix.shape
    row2, col2 = row // 2, col // 2
    return matrix[:row2, :col2], matrix[:row2, col2:], matrix[row2:, :col2], matrix[row2:, col2:]

def strassens(A, B):
    n = A.shape[0]

    # Base case: 1x1 matrix
    if n == 1:
        return A * B

    # Split matrices
    a, b, c, d = split(A)
    e, f, g, h = split(B)

    # 7 products (Strassen’s trick)
    p1 = strassens(a, f - h)
    p2 = strassens(a + b, h)
    p3 = strassens(c + d, e)
    p4 = strassens(d, g - e)
    p5 = strassens(a + d, e + h)
    p6 = strassens(b - d, g + h)
    p7 = strassens(a - c, e + f)

    # Quadrants of result
    c11 = p5 + p4 - p2 + p6
    c12 = p1 + p2
    c21 = p3 + p4
    c22 = p1 + p5 - p3 - p7

    # Combine quadrants
    top = np.hstack((c11, c12))
    bottom = np.hstack((c21, c22))
    c = np.vstack((top, bottom))

    return c


# Driver code
A = np.array([[1, 1, 1, 1],
              [2, 2, 2, 2],
              [3, 3, 3, 3],
              [4, 4, 4, 4]])

B = np.array([[1, 1, 1, 1],
              [2, 2, 2, 2],
              [3, 3, 3, 3],
              [4, 4, 4, 4]])

print("Strassen’s Multiplication Result:")
print(strassens(A, B))


Strassen’s Multiplication Result:
[[10 10 10 10]
 [20 20 20 20]
 [30 30 30 30]
 [40 40 40 40]]
